# Generated by Django 3.2.3 on 2021-05-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='content',
        ),
    ]
