# Generated by Django 3.2.3 on 2021-06-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210622_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
